### ISSUE TITLE
Please add compatibility with Vaadin 8

### ISSUE THREAD

**Issue by mvysny** [mstahv/addon-test-helpers#12]
Currently when the `TServer` class is run on Vaadin 8, it fails with:

```
2017-03-08 15:59:28.483:WARN:oejuc.AbstractLifeCycle:main: FAILED o.e.j.w.WebAppContext@6a28ffa4{/,file:/home/mavi/work/vaadin/add-ons/failover-vaadin/target/testwebapp/,STARTING}{target/testwebapp}: java.lang.NoSuchMethodError: com.vaadin.server.VaadinServletService.addSessionInitListener(Lcom/vaadin/server/SessionInitListener;)V
java.lang.NoSuchMethodError: com.vaadin.server.VaadinServletService.addSessionInitListener(Lcom/vaadin/server/SessionInitListener;)V
	at org.vaadin.addonhelpers.TServer.configureVaadinService(TServer.java:116)
	at org.vaadin.addonhelpers.TServer$VaadinTestServlet.init(TServer.java:135)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1345)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1338)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:501)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.vaadin.addonhelpers.TServer.startServer(TServer.java:69)
	at org.vaadin.addonhelpers.TServer.startServer(TServer.java:38)
	at com.vaadin.failover.uiserver.Server.main(Server.java:13)
```

**Comment by mvysny** [comment]
Also, later on it will fail because of missing Container :-)

**Comment by dve** [comment]
Are you using the vaadin8 branch?

**Comment by mvysny** [comment]
I apologize, didn't noticed that branch. Built from sources and referenced 2.0-SNAPSHOT from my project, now the Server/TServer starts properly. However, the interesting thing is that the Grid, which should list all *UI classes shows no columns. I have debugged the TListUI and everything seems to be in order - my one UI class is detected properly, columns are added to the Grid, yet the Grid shows empty. Attaching screenshot.
![screenshot from 2017-03-08 17-12-23](https://cloud.githubusercontent.com/assets/254091/23709622/b86d5a34-0422-11e7-8e8c-95a690f39ed2.png)

**Comment by mstahv** [comment]
@mvysny Can yo share the project with me? There is probably some execption in v8 branch when crawling for available tests that would need to be handled properly.

We should probably also switch the master to V8.

**Comment by mvysny** [comment]
@mstahv Sure. First please `mvn clean install -DskipTests` of `addon-test-helpers` branch `vaadin8`. Then clone https://github.com/mvysny/failover-vaadin branch `vaadin8port` and run the `Server` class.

**Comment by mstahv** [comment]
I tried that and it worked fine for me. Maybe time has healed it (8.0.X)  :-) Can you try it out as well?

**Comment by mvysny** [comment]
@mstahv oh I'm so sorry, I forgot to recompile the widgetset :( It's my fault. So probably Grid v8 has different comm protocol than Grid V7 and thus would not receive any data. Curiously Vaadin did not warned me of mismatching client/server version... Nevertheless, things work for me now. Thanks!
